# Generated by Django 4.2.3 on 2023-10-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0024_alter_expense_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="adjust",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
