# Generated by Django 4.2.3 on 2023-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0026_salesorder_advance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="adjust",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
