# Generated by Django 4.2.3 on 2023-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0027_alter_salesorder_adjust"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="cheque_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="upi_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
