# Generated by Django 4.2.3 on 2023-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0028_salesorder_cheque_id_salesorder_upi_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="adjust",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
